### ISSUE TITLE
[TECH] Communication Layer

### ISSUE THREAD

**Issue by anatoliisku** [extreme-startup/questionator#44]
**!!!Please check with Architect in order to proceed!!!**

**To Do**: 
- provide an ability for the Admin/Trainer to start the server;
- allow the participants to register themselves (e.g. by providing a URL (usually their local IP address));
- the server needs to send HTTP requests containing questions to the registered URLs;
- participants have to implement an application that is capable of answering the questions send by the server (response to HTTP GET requests).

**NOTES**:
- Provide an ability to join the competition (Client -> Server)
- Get questions on the Client side
- Provide answers for the Server

**IMPORTANT**: During the session more and more questions are added, so the participants have to extend their application to gather more points. App uses HTTP for interacting with the participant, so everyone can use the stack of their choice.

**Comment by kolesnik** [comment]
Documentation for is avaliable here: https://github.com/extreme-startup/questionator/wiki/Participation-in-the-game
https://github.com/extreme-startup/questinator-connector
https://github.com/extreme-startup/contender-nodeJS-client
